/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'
import type {
  CreateServerFileRoute,
  ServerFileRoutesByPath,
} from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LibrariesRouteRouteImport } from './routes/_libraries/route'
import { Route as LibrariesIndexRouteImport } from './routes/_libraries/index'
import { Route as LibrariesTermsRouteImport } from './routes/_libraries/terms'
import { Route as LibrariesPrivacyRouteImport } from './routes/_libraries/privacy'
import { Route as LibrariesEthosRouteImport } from './routes/_libraries/ethos'
import { Route as LibrariesBlogRouteImport } from './routes/_libraries/blog'
import { Route as LibrariesBlogIndexRouteImport } from './routes/_libraries/blog.index'
import { Route as LibrariesBlogSplatRouteImport } from './routes/_libraries/blog.$'

const LibrariesRouteRoute = LibrariesRouteRouteImport.update({
  id: '/_libraries',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesIndexRoute = LibrariesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibrariesRouteRoute,
} as any)
const LibrariesTermsRoute = LibrariesTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LibrariesRouteRoute,
} as any)
const LibrariesPrivacyRoute = LibrariesPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LibrariesRouteRoute,
} as any)
const LibrariesEthosRoute = LibrariesEthosRouteImport.update({
  id: '/ethos',
  path: '/ethos',
  getParentRoute: () => LibrariesRouteRoute,
} as any)
const LibrariesBlogRoute = LibrariesBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => LibrariesRouteRoute,
} as any)
const LibrariesBlogIndexRoute = LibrariesBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibrariesBlogRoute,
} as any)
const LibrariesBlogSplatRoute = LibrariesBlogSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LibrariesBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/blog': typeof LibrariesBlogRouteWithChildren
  '/ethos': typeof LibrariesEthosRoute
  '/privacy': typeof LibrariesPrivacyRoute
  '/terms': typeof LibrariesTermsRoute
  '/': typeof LibrariesIndexRoute
  '/blog/$': typeof LibrariesBlogSplatRoute
  '/blog/': typeof LibrariesBlogIndexRoute
}
export interface FileRoutesByTo {
  '/ethos': typeof LibrariesEthosRoute
  '/privacy': typeof LibrariesPrivacyRoute
  '/terms': typeof LibrariesTermsRoute
  '/': typeof LibrariesIndexRoute
  '/blog/$': typeof LibrariesBlogSplatRoute
  '/blog': typeof LibrariesBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_libraries': typeof LibrariesRouteRouteWithChildren
  '/_libraries/blog': typeof LibrariesBlogRouteWithChildren
  '/_libraries/ethos': typeof LibrariesEthosRoute
  '/_libraries/privacy': typeof LibrariesPrivacyRoute
  '/_libraries/terms': typeof LibrariesTermsRoute
  '/_libraries/': typeof LibrariesIndexRoute
  '/_libraries/blog/$': typeof LibrariesBlogSplatRoute
  '/_libraries/blog/': typeof LibrariesBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/blog'
    | '/ethos'
    | '/privacy'
    | '/terms'
    | '/'
    | '/blog/$'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to: '/ethos' | '/privacy' | '/terms' | '/' | '/blog/$' | '/blog'
  id:
    | '__root__'
    | '/_libraries'
    | '/_libraries/blog'
    | '/_libraries/ethos'
    | '/_libraries/privacy'
    | '/_libraries/terms'
    | '/_libraries/'
    | '/_libraries/blog/$'
    | '/_libraries/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LibrariesRouteRoute: typeof LibrariesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_libraries': {
      id: '/_libraries'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LibrariesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_libraries/blog': {
      id: '/_libraries/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof LibrariesBlogRouteImport
      parentRoute: typeof LibrariesRouteRoute
    }
    '/_libraries/ethos': {
      id: '/_libraries/ethos'
      path: '/ethos'
      fullPath: '/ethos'
      preLoaderRoute: typeof LibrariesEthosRouteImport
      parentRoute: typeof LibrariesRouteRoute
    }
    '/_libraries/privacy': {
      id: '/_libraries/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof LibrariesPrivacyRouteImport
      parentRoute: typeof LibrariesRouteRoute
    }
    '/_libraries/terms': {
      id: '/_libraries/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof LibrariesTermsRouteImport
      parentRoute: typeof LibrariesRouteRoute
    }
    '/_libraries/': {
      id: '/_libraries/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LibrariesIndexRouteImport
      parentRoute: typeof LibrariesRouteRoute
    }
    '/_libraries/blog/$': {
      id: '/_libraries/blog/$'
      path: '/$'
      fullPath: '/blog/$'
      preLoaderRoute: typeof LibrariesBlogSplatRouteImport
      parentRoute: typeof LibrariesBlogRoute
    }
    '/_libraries/blog/': {
      id: '/_libraries/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof LibrariesBlogIndexRouteImport
      parentRoute: typeof LibrariesBlogRoute
    }
  }
}

declare module './routes/_libraries/route' {
  const createFileRoute: CreateFileRoute<
    '/_libraries',
    FileRoutesByPath['/_libraries']['parentRoute'],
    FileRoutesByPath['/_libraries']['id'],
    FileRoutesByPath['/_libraries']['path'],
    FileRoutesByPath['/_libraries']['fullPath']
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath['/_libraries']['parentRoute'],
    ServerFileRoutesByPath['/_libraries']['id'],
    ServerFileRoutesByPath['/_libraries']['path'],
    ServerFileRoutesByPath['/_libraries']['fullPath'],
    unknown
  >
}
declare module './routes/_libraries/blog' {
  const createFileRoute: CreateFileRoute<
    '/_libraries/blog',
    FileRoutesByPath['/_libraries/blog']['parentRoute'],
    FileRoutesByPath['/_libraries/blog']['id'],
    FileRoutesByPath['/_libraries/blog']['path'],
    FileRoutesByPath['/_libraries/blog']['fullPath']
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath['/_libraries/blog']['parentRoute'],
    ServerFileRoutesByPath['/_libraries/blog']['id'],
    ServerFileRoutesByPath['/_libraries/blog']['path'],
    ServerFileRoutesByPath['/_libraries/blog']['fullPath'],
    unknown
  >
}
declare module './routes/_libraries/ethos' {
  const createFileRoute: CreateFileRoute<
    '/_libraries/ethos',
    FileRoutesByPath['/_libraries/ethos']['parentRoute'],
    FileRoutesByPath['/_libraries/ethos']['id'],
    FileRoutesByPath['/_libraries/ethos']['path'],
    FileRoutesByPath['/_libraries/ethos']['fullPath']
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath['/_libraries/ethos']['parentRoute'],
    ServerFileRoutesByPath['/_libraries/ethos']['id'],
    ServerFileRoutesByPath['/_libraries/ethos']['path'],
    ServerFileRoutesByPath['/_libraries/ethos']['fullPath'],
    unknown
  >
}
declare module './routes/_libraries/privacy' {
  const createFileRoute: CreateFileRoute<
    '/_libraries/privacy',
    FileRoutesByPath['/_libraries/privacy']['parentRoute'],
    FileRoutesByPath['/_libraries/privacy']['id'],
    FileRoutesByPath['/_libraries/privacy']['path'],
    FileRoutesByPath['/_libraries/privacy']['fullPath']
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath['/_libraries/privacy']['parentRoute'],
    ServerFileRoutesByPath['/_libraries/privacy']['id'],
    ServerFileRoutesByPath['/_libraries/privacy']['path'],
    ServerFileRoutesByPath['/_libraries/privacy']['fullPath'],
    unknown
  >
}
declare module './routes/_libraries/terms' {
  const createFileRoute: CreateFileRoute<
    '/_libraries/terms',
    FileRoutesByPath['/_libraries/terms']['parentRoute'],
    FileRoutesByPath['/_libraries/terms']['id'],
    FileRoutesByPath['/_libraries/terms']['path'],
    FileRoutesByPath['/_libraries/terms']['fullPath']
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath['/_libraries/terms']['parentRoute'],
    ServerFileRoutesByPath['/_libraries/terms']['id'],
    ServerFileRoutesByPath['/_libraries/terms']['path'],
    ServerFileRoutesByPath['/_libraries/terms']['fullPath'],
    unknown
  >
}
declare module './routes/_libraries/index' {
  const createFileRoute: CreateFileRoute<
    '/_libraries/',
    FileRoutesByPath['/_libraries/']['parentRoute'],
    FileRoutesByPath['/_libraries/']['id'],
    FileRoutesByPath['/_libraries/']['path'],
    FileRoutesByPath['/_libraries/']['fullPath']
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath['/_libraries/']['parentRoute'],
    ServerFileRoutesByPath['/_libraries/']['id'],
    ServerFileRoutesByPath['/_libraries/']['path'],
    ServerFileRoutesByPath['/_libraries/']['fullPath'],
    unknown
  >
}
declare module './routes/_libraries/blog.$' {
  const createFileRoute: CreateFileRoute<
    '/_libraries/blog/$',
    FileRoutesByPath['/_libraries/blog/$']['parentRoute'],
    FileRoutesByPath['/_libraries/blog/$']['id'],
    FileRoutesByPath['/_libraries/blog/$']['path'],
    FileRoutesByPath['/_libraries/blog/$']['fullPath']
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath['/_libraries/blog/$']['parentRoute'],
    ServerFileRoutesByPath['/_libraries/blog/$']['id'],
    ServerFileRoutesByPath['/_libraries/blog/$']['path'],
    ServerFileRoutesByPath['/_libraries/blog/$']['fullPath'],
    unknown
  >
}
declare module './routes/_libraries/blog.index' {
  const createFileRoute: CreateFileRoute<
    '/_libraries/blog/',
    FileRoutesByPath['/_libraries/blog/']['parentRoute'],
    FileRoutesByPath['/_libraries/blog/']['id'],
    FileRoutesByPath['/_libraries/blog/']['path'],
    FileRoutesByPath['/_libraries/blog/']['fullPath']
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath['/_libraries/blog/']['parentRoute'],
    ServerFileRoutesByPath['/_libraries/blog/']['id'],
    ServerFileRoutesByPath['/_libraries/blog/']['path'],
    ServerFileRoutesByPath['/_libraries/blog/']['fullPath'],
    unknown
  >
}

interface LibrariesBlogRouteChildren {
  LibrariesBlogSplatRoute: typeof LibrariesBlogSplatRoute
  LibrariesBlogIndexRoute: typeof LibrariesBlogIndexRoute
}

const LibrariesBlogRouteChildren: LibrariesBlogRouteChildren = {
  LibrariesBlogSplatRoute: LibrariesBlogSplatRoute,
  LibrariesBlogIndexRoute: LibrariesBlogIndexRoute,
}

const LibrariesBlogRouteWithChildren = LibrariesBlogRoute._addFileChildren(
  LibrariesBlogRouteChildren,
)

interface LibrariesRouteRouteChildren {
  LibrariesBlogRoute: typeof LibrariesBlogRouteWithChildren
  LibrariesEthosRoute: typeof LibrariesEthosRoute
  LibrariesPrivacyRoute: typeof LibrariesPrivacyRoute
  LibrariesTermsRoute: typeof LibrariesTermsRoute
  LibrariesIndexRoute: typeof LibrariesIndexRoute
}

const LibrariesRouteRouteChildren: LibrariesRouteRouteChildren = {
  LibrariesBlogRoute: LibrariesBlogRouteWithChildren,
  LibrariesEthosRoute: LibrariesEthosRoute,
  LibrariesPrivacyRoute: LibrariesPrivacyRoute,
  LibrariesTermsRoute: LibrariesTermsRoute,
  LibrariesIndexRoute: LibrariesIndexRoute,
}

const LibrariesRouteRouteWithChildren = LibrariesRouteRoute._addFileChildren(
  LibrariesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LibrariesRouteRoute: LibrariesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
